#@ load("@ytt:data", "data")
apiVersion: apps/v1
kind: Deployment
metadata:
  name: #@ data.values.name
spec:
  selector:
    matchLabels:
      app: #@ data.values.name
  template:
    metadata:
      labels:
          app: #@ data.values.name
    spec:
      containers:
      - name: #@ data.values.name
        image: #@ data.values.image
        command: run
        ports:
        - containerPort: 8000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name:  #@ data.values.name
  labels:
    app: #@ data.values.name
spec:
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app:  #@ data.values.name
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name:  #@ data.values.name
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: letsencrypt-dns-prod-issuer
  labels:
    app: #@ data.values.name
spec:
  - hosts:
      - #@ data.values.host
      secretName: letsencrypt-wildcard-shishov-ml-tls
  rules:
  - host: #@ data.values.host
    http:
      paths:
      - backend:
          serviceName: #@ data.values.name
          servicePort: 80