#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: cognitive-content-pvc
#  labels:
#    app: cognitive
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 10Gi
#---
#apiVersion: storage.k8s.io/v1
#kind: StorageClass
#metadata:
#  name: local-sc
#provisioner: docker.io/hostpath
#reclaimPolicy: Delete
#volumeBindingMode: Immediate
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: local-pv
#  labels:
#    type: local
#spec:
#  storageClassName: manual
#  capacity:
#    storage: 5Gi
#  accessModes:
#    - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Delete
#  hostPath:
#    path: "/mnt/data"
#    type: DirectoryOrCreate
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: cognitive-content-pvc
#  labels:
#    app: cognitive
#spec:
#  accessModes:
#    - ReadWriteOnce
#  volumeMode: Filesystem
#  resources:
#    requests:
#      storage: 5Gi
#  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cognitive-content-pvc
  labels:
    app: cognitive
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage