version: '3.3'

services:
  cognitive:
    build: .
    environment:
      DJANGO_SECRET_KEY: ${COGNITIVE_DJANGO_SECRET_KEY:-super-secret-key}
      DJANGO_DB_URL: ${COGNITIVE_DJANGO_DB_URL:-mysql://cognitive:cognitive@db:3306/cognitive}
      DJANGO_DEBUG: ${COGNITIVE_DJANGO_DEBUG:-False}
      DJANGO_HOST: ${COGNITIVE_DJANGO_HOST}
      PORT: ${COGNITIVE_PORT:-8000}
    command: ${COGNITIVE_CMD:-run}
    restart: always
    volumes:
      - ${COGNITIVE_STATIC_PATH:-./data/static}:/var/cognitive/static
      - ${COGNITIVE_MEDIA_PATH:-./data/media}:/var/cognitive/media
      - ${COGNITIVE_MODULES_PATH:-./data/modules}:/var/cognitive/modules
      - ${COGNITIVE_RESULTS_PATH:-./data/results}:/var/cognitive/results
      - ${COGNITIVE_LOGS_PATH:-./data/logs}:/var/log/cognitive
    ports:
      - ${COGNITIVE_PORT:-8000}:${COGNITIVE_PORT:-8000}
    expose:
      - ${COGNITIVE_PORT:-8000}
    networks:
      - db_network
      - webproxy
    depends_on:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --innodb-buffer-pool-size=64M --key_buffer_size=32M --innodb_log_file_size=64M --query_cache_size=0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${COGNITIVE_MYSQL_ROOT_PASSWORD:-strong-one-mysql-password}
      MYSQL_DATABASE: ${COGNITIVE_MYSQL_DATABASE:-cognitive}
      MYSQL_USER: ${COGNITIVE_MYSQL_USER:-cognitive}
      MYSQL_PASSWORD: ${COGNITIVE_MYSQL_PASSWORD:-cognitive}
    hostname: ${COGNITIVE_MYSQL_HOSTNAME:-db}
    volumes:
      - ${COGNITIVE_MYSQL_DATA_PATH:-./data/mysql}:/var/lib/mysql
    networks:
      - db_network

networks:
  db_network:
    driver: bridge
  webproxy:
    external:
      name: ${COGNITIVE_NETWORK:-bridge}
