# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-08 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cognitive_tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='key',
            field=models.SlugField(default='somekey', max_length=255, unique=True, verbose_name='key'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='surveyresultvalue',
            name='comment',
            field=models.TextField(blank=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='testresultvalue',
            name='comment',
            field=models.TextField(blank=True, verbose_name='comment'),
        ),
        migrations.AlterUniqueTogether(
            name='surveymark',
            unique_together=set([('survey', 'key')]),
        ),
        migrations.AlterUniqueTogether(
            name='surveyresultvalue',
            unique_together=set([('result', 'mark')]),
        ),
        migrations.AlterUniqueTogether(
            name='testmark',
            unique_together=set([('test', 'key')]),
        ),
        migrations.AlterUniqueTogether(
            name='testresultfile',
            unique_together=set([('name', 'result')]),
        ),
        migrations.AlterUniqueTogether(
            name='testresulttextdata',
            unique_together=set([('name', 'result')]),
        ),
        migrations.AlterUniqueTogether(
            name='testresultvalue',
            unique_together=set([('result', 'mark')]),
        ),
    ]
