# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-08 17:58
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cognitive_tests', '0002_auto_20170108_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='survey/images'),
        ),
    ]
