# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 20:08
from __future__ import unicode_literals

import cognitive_tests.models
import cognitive_tests.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cognitive_tests', '0002_auto_20160906_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=cognitive_tests.models.TestFile.get_filename)),
                ('test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='cognitive_tests.TestResult')),
            ],
        ),
        migrations.CreateModel(
            name='TestTextData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='cognitive_tests.TestResult')),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='auto_save_data_to_file',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='webtest',
            name='js_script_files',
            field=cognitive_tests.utils.SeparatedValuesField(blank=True, max_length=1024, null=True),
        ),
    ]
