# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cognitive_tests', '0003_auto_20160907_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='testfile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testfile',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testtextdata',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testtextdata',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testtextdata',
            name='test_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_data', to='cognitive_tests.TestResult'),
        ),
    ]
