# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-08 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cognitive_tests', '0003_survey_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveymark',
            name='unit',
            field=models.CharField(blank=True, max_length=255, verbose_name='unit'),
        ),
        migrations.AddField(
            model_name='testmark',
            name='unit',
            field=models.CharField(blank=True, max_length=255, verbose_name='unit'),
        ),
    ]
