# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 01:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cognitive_tests', '0004_auto_20160908_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AlterModelOptions(
            name='testfile',
            options={'verbose_name': 'Файлы результатов', 'verbose_name_plural': 'Файлы результатов'},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'verbose_name': 'Результаты', 'verbose_name_plural': 'Результаты'},
        ),
        migrations.AlterModelOptions(
            name='testtextdata',
            options={'verbose_name': 'Данные результатов', 'verbose_name_plural': 'Данные результатов'},
        ),
        migrations.AlterModelOptions(
            name='webtest',
            options={'verbose_name': 'Веб тест', 'verbose_name_plural': 'Веб тесты'},
        ),
        migrations.RenameField(
            model_name='test',
            old_name='enabled',
            new_name='active',
        ),
        migrations.RemoveField(
            model_name='testfile',
            name='created',
        ),
        migrations.RemoveField(
            model_name='testtextdata',
            name='created',
        ),
    ]
