# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-09 00:31
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cognitive_tests', '0004_auto_20170108_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='short description'),
        ),
        migrations.AddField(
            model_name='surveymark',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='visible'),
        ),
        migrations.AddField(
            model_name='testmark',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='visible'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='survey/images', verbose_name='image'),
        ),
    ]
