# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 16:11
from __future__ import unicode_literals

import cognitive_tests.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cognitive_tests', '0005_auto_20160909_0447'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebTestGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Группа тестов',
                'verbose_name_plural': 'Группы тестов',
            },
        ),
        migrations.CreateModel(
            name='WebTestMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cognitive_tests.WebTestGroup')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='WebTestResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resources', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Ресурс',
                'verbose_name_plural': 'Ресурсы',
            },
        ),
        migrations.AlterModelOptions(
            name='testfile',
            options={'verbose_name': 'Файлы результата', 'verbose_name_plural': 'Файлы результатов'},
        ),
        migrations.AlterModelOptions(
            name='testtextdata',
            options={'verbose_name': 'Данные результата', 'verbose_name_plural': 'Данные результатов'},
        ),
        migrations.RemoveField(
            model_name='webtest',
            name='js_script_files',
        ),
        migrations.RemoveField(
            model_name='webtest',
            name='resources_path',
        ),
        migrations.AlterField(
            model_name='participant',
            name='age',
            field=models.PositiveSmallIntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='allow_info_usage',
            field=models.BooleanField(verbose_name='Разрешение на публикацию данных'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.BooleanField(choices=[(True, 'Male'), (False, 'Female')], verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_test',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Последний тест'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='session',
            field=models.CharField(max_length=1000, verbose_name='Ключ сессии'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='test',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='test',
            name='auto_save_data_to_file',
            field=models.BooleanField(default=False, verbose_name='Автоматически сохранять данные в файлы'),
        ),
        migrations.AlterField(
            model_name='test',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='testfile',
            name='file',
            field=models.FileField(upload_to=cognitive_tests.models.TestFile.get_filename, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='testfile',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя файла'),
        ),
        migrations.AlterField(
            model_name='testfile',
            name='test_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='cognitive_tests.TestResult', verbose_name='Результат'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='cognitive_tests.Participant', verbose_name='Участник'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='cognitive_tests.Test', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='testtextdata',
            name='data',
            field=models.TextField(verbose_name='Данные'),
        ),
        migrations.AlterField(
            model_name='testtextdata',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя данных'),
        ),
        migrations.AlterField(
            model_name='testtextdata',
            name='test_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_data', to='cognitive_tests.TestResult', verbose_name='Результат'),
        ),
        migrations.AlterField(
            model_name='webtest',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='webtest',
            name='js_inline_script',
            field=models.TextField(blank=True, null=True, verbose_name='JS скрипт'),
        ),
        migrations.AlterField(
            model_name='webtest',
            name='record_audio',
            field=models.BooleanField(default=False, verbose_name='Записывать аудио'),
        ),
        migrations.AlterField(
            model_name='webtest',
            name='record_mouse',
            field=models.BooleanField(default=False, verbose_name='Записывать события мыши'),
        ),
        migrations.AlterField(
            model_name='webtest',
            name='record_video',
            field=models.BooleanField(default=False, verbose_name='Записывать видео'),
        ),
        migrations.AlterField(
            model_name='webtest',
            name='test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='web_test', to='cognitive_tests.Test', verbose_name='Тест'),
        ),
        migrations.AddField(
            model_name='webtestmembership',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cognitive_tests.WebTest'),
        ),
        migrations.AddField(
            model_name='webtestgroup',
            name='members',
            field=models.ManyToManyField(through='cognitive_tests.WebTestMembership', to='cognitive_tests.WebTest'),
        ),
        migrations.AddField(
            model_name='webtestgroup',
            name='resources',
            field=models.ManyToManyField(to='cognitive_tests.WebTestResource'),
        ),
        migrations.AddField(
            model_name='webtest',
            name='resources',
            field=models.ManyToManyField(to='cognitive_tests.WebTestResource'),
        ),
    ]
