# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-10 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cognitive_tests', '0006_auto_20170109_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveymark',
            name='key',
            field=models.SlugField(max_length=255, verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='surveyresultvalue',
            name='value',
            field=jsonfield.fields.JSONField(verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='testmark',
            name='key',
            field=models.SlugField(max_length=255, verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='testresultvalue',
            name='value',
            field=jsonfield.fields.JSONField(verbose_name='value'),
        ),
    ]
