# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cognitive_tests', '0006_auto_20160910_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webtestgroup',
            old_name='members',
            new_name='tests',
        ),
    ]
