# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 04:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cognitive_tests', '0007_auto_20170110_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='survey_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='cognitive_tests.SurveyResult', verbose_name='survey result'),
        ),
        migrations.AlterUniqueTogether(
            name='testresult',
            unique_together=set([('id', 'survey_result')]),
        ),
    ]
