# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cognitive_tests', '0007_auto_20160910_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webtestmembership',
            name='group',
        ),
        migrations.RemoveField(
            model_name='webtestmembership',
            name='test',
        ),
        migrations.RemoveField(
            model_name='webtestgroup',
            name='tests',
        ),
        migrations.AddField(
            model_name='webtest',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Тесты', to='cognitive_tests.WebTestGroup', verbose_name='Группа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webtest',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок в группе'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='webtestgroup',
            name='resources',
            field=models.ManyToManyField(to='cognitive_tests.WebTestResource', verbose_name='Ресурсы'),
        ),
        migrations.DeleteModel(
            name='WebTestMembership',
        ),
    ]
