# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cognitive_tests', '0008_auto_20160910_1958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webtest',
            options={'ordering': ['-order'], 'verbose_name': 'Веб тест', 'verbose_name_plural': 'Веб тесты'},
        ),
        migrations.AlterModelOptions(
            name='webtestgroup',
            options={'verbose_name': 'Группа веб тестов', 'verbose_name_plural': 'Группы веб тестов'},
        ),
        migrations.AddField(
            model_name='webtest',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание (markdown)'),
        ),
        migrations.AlterField(
            model_name='webtestgroup',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание (markdown)'),
        ),
    ]
