# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 04:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cognitive_tests', '0008_auto_20170112_0752'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testresult',
            unique_together=set([('test', 'survey_result')]),
        ),
    ]
