# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cognitive_tests', '0010_auto_20170112_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveymark',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'numeric'), ('STRING', 'string'), ('DATETIME', 'datetime'), ('NUMERIC_ARRAY', 'numeric array'), ('JSON', 'json')], default='NUMERIC', max_length=50, verbose_name='data types'),
        ),
        migrations.AddField(
            model_name='testmark',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'numeric'), ('STRING', 'string'), ('DATETIME', 'datetime'), ('NUMERIC_ARRAY', 'numeric array'), ('JSON', 'json')], default='NUMERIC', max_length=50, verbose_name='data types'),
        ),
        migrations.AlterField(
            model_name='surveymark',
            name='format',
            field=models.CharField(blank=True, max_length=255, verbose_name='format'),
        ),
        migrations.AlterField(
            model_name='testmark',
            name='format',
            field=models.CharField(blank=True, max_length=255, verbose_name='format'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='survey_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='test_results', to='cognitive_tests.SurveyResult', verbose_name='survey result'),
        ),
    ]
