# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-15 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cognitive_tests', '0011_auto_20170112_2033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ('-created',), 'verbose_name': 'module', 'verbose_name_plural': 'modules'},
        ),
        migrations.RemoveField(
            model_name='module',
            name='imported',
        ),
        migrations.AddField(
            model_name='module',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated'),
        ),
    ]
