# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-15 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cognitive_tests', '0012_auto_20170115_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='last_test',
        ),
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[(('male',), 'male'), (('female',), 'female')], max_length=50, verbose_name='gender'),
        ),
    ]
