# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cognitive_tests', '0013_auto_20170116_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresult',
            name='processed',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='processed',
        ),
        migrations.AddField(
            model_name='surveyresult',
            name='processing_ended',
            field=models.DateTimeField(blank=True, null=True, verbose_name='processing ended'),
        ),
        migrations.AddField(
            model_name='surveyresult',
            name='processing_started',
            field=models.DateTimeField(blank=True, null=True, verbose_name='processing started'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='processing_ended',
            field=models.DateTimeField(blank=True, null=True, verbose_name='processing ended'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='processing_started',
            field=models.DateTimeField(blank=True, null=True, verbose_name='processing started'),
        ),
    ]
