# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-22 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cognitive_tests', '0014_auto_20170117_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='test/images', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='test',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='short description'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=50, verbose_name='gender'),
        ),
    ]
