name: Build and deploy

on:
  push:
    branches:
      - master

jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - name: Build and push Docker images
#      uses: docker/build-push-action@v1.1.0
#      with:
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}
#        registry: ${{ secrets.DOCKER_REGISTRY }}
#        tag_with_ref: true
#        repository: bshishov/cognitive
  deploy:
    runs-on: ubuntu-latest
    #needs: build
    steps:
      - uses: actions/checkout@v2
      #- name: Install ytt (yaml templating)
      #  run: |
      #    wget -q https://github.com/k14s/ytt/releases/download/v0.28.0/ytt-linux-amd64
      #    chmod +x ytt-linux-amd64
      #- name: Generate deployment
      #  run: ./ytt-linux-amd64 -f .k8s/ > deployment.rendered.yml
      - name: Init kube config
        env:
          KUBECONFIG: ${{secrets.KUBECONFIG}}
        run: printf "$KUBECONFIG" > .kubeconfig
      - name: K8S apply
        run: |
          docker run --rm -v ${PWD}/.kubeconfig:/.kube/config -v ${PWD}/.k8s/deployment.yml:/opt/deployment.yml bitnami/kubectl apply -f /opt/deployment.yml